[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/L_WeepingMoors
EditorStartupMap=/Game/Maps/L_WeepingMoors
GlobalDefaultGameMode=/Script/HollowCrown.HCGameMode

[/Script/Engine.RendererSettings]
; The Hollow Crown targets stylized dark realism using UE5's modern feature set.
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Lumen.HardwareRayTracing=False
r.Nanite.ProjectEnabled=True
r.VirtualTextures=True
r.Shadow.Virtual.Enable=1
r.DefaultFeature.AutoExposure=True
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.Bloom=True
r.DefaultFeature.AmbientOcclusion=True
r.AllowStaticLighting=False
r.SkinCache.CompileShaders=True
; Permanent-twilight mood: lean on volumetric fog and exponential height fog.
r.VolumetricFog=1

[/Script/WorldPartitionEditor.WorldPartitionEditorSettings]
CommandletClass=Class'/Script/UnrealEd.WorldPartitionConvertCommandlet'

[/Script/Engine.PhysicsSettings]
DefaultGravityZ=-980.000000
PhysicsPrediction=(bEnablePhysicsPrediction=False)

[/Script/AIModule.AISystem]
bEnableDebuggerPlugin=True

[/Script/Engine.CollisionProfile]
+Profiles=(Name="HCWeapon",CollisionEnabled=QueryOnly,bCanModify=True,ObjectTypeName="WorldDynamic",CustomResponses=((Channel="Pawn",Response=ECR_Overlap)),HelpMessage="Melee weapon trace volume.")
